name: Building
on: [push, pull_request]

jobs:
  build:
    name: Building SCLAlertView
    runs-on: macOS-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Xcode version
        uses: maxim-lobanov/setup-xcode@v1.1
        with:
          xcode-version: 12.0.0
      - name: Building iOS app
        run: exec ./.github/scripts/build_app.sh
